cat CompositeDC/sim1_notag_CompositeDC_*ErrorToTruth* > friedman1_CompositeDC_ErrorToTruth.txt
cat CompositeThirds/sim1_notag_CompositeThirds_*ErrorToTruth* > friedman1_CompositeThirds_ErrorToTruth.txt
cat CompositeRob/sim1_notag_CompositeRob_ErrorToTruthCurrent_* > friedman1_CompositeRob_ErrorToTruth.txt
cat CompositeRob/sim1_notag_CompositeRob_ErrorToTruthCurrent.ErrorOptimisim.lambdas_* > friedman1_CompositeRob_ErrorToTruth.ErrorOptimisim.Lambdas.txt
cat CompositeRob/sim1_notag_CompositeRob_ErrorToTruthCurrent.errorU.lambdas_* > friedman1_CompositeRob_ErrorToTruth.errorU.lambdas.txt
cat CompositeRob/sim1_notag_CompositeRob_ErrorToTruthCurrent.error.lambdas_* > friedman1_CompositeRob_ErrorToTruth.error.lambdas.txt


# with 500 in training set


cat CompositeDC/sim1_500_CompositeDC_*ErrorToTruth* > friedman1_500_CompositeDC_ErrorToTruth.txt
cat CompositeThirds/sim1_500_CompositeThirds_*ErrorToTruth* > friedman1_500_CompositeThirds_ErrorToTruth.txt
cat CompositeRob/sim1_500_CompositeRob_*ErrorToTruthCurrent_* > friedman1_500_CompositeRob_ErrorToTruth.txt
cat CompositeRob/sim1_500_CompositeRob_*ErrorToTruthCurrent.ErrorOptimisim.lambdas_* > friedman1_500_CompositeRob_ErrorToTruth.ErrorOptimisim.Lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_*ErrorToTruthCurrent.errorU.lambdas_* > friedman1_500_CompositeRob_ErrorToTruth.errorU.lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_*ErrorToTruthCurrent.error.lambdas_* > friedman1_500_CompositeRob_ErrorToTruth.error.lambdas.txt




# with 500 in training set  and the same lambda grid


cat CompositeDC/sim1_500_CompositeDC_Train500_uplim_*ErrorToTruth* > friedman1_500_CompositeDC_Train500_uplim_ErrorToTruth.txt
cat CompositeThirds/sim1_500_CompositeThirds_500_uplim_*ErrorToTruth* > friedman1_500_CompositeThirds_500_uplim_ErrorToTruth.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_*ErrorToTruthCurrent_* > friedman1_500_CompositeRob_500_uplim_ErrorToTruth.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_*ErrorToTruthCurrent.ErrorOptimisim.lambdas_* > friedman1_500_CompositeRob_500_uplim_ErrorToTruth.ErrorOptimisim.Lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_*ErrorToTruthCurrent.errorU.lambdas_* > friedman1_500_CompositeRob_500_uplim_ErrorToTruth.errorU.lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_*ErrorToTruthCurrent.error.lambdas_* > friedman1_500_CompositeRob_500_uplim_ErrorToTruth.error.lambdas.txt



cat CompositeDC/sim1_500_CompositeDC_Train500_uplim_*MinErrorLambda* > friedman1_500_CompositeDC_Train500_uplim_MinErrorLambda.txt
cat CompositeThirds/sim1_500_CompositeThirds_500_uplim_*MinErrorLambda* > friedman1_500_CompositeThirds_500_uplim_MinErrorLambda.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_MinErrorLambda* > friedman1_500_CompositeRob_500_uplim_MinErrorLambda.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_MinErrorLambda_ErrorOptimisim.lambdas_* > friedman1_500_CompositeRob_500_uplim_MinErrorLambda.ErrorOptimisim.Lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_MinErrorLambda_errorU.lambdas_* > friedman1_500_CompositeRob_500_uplim_MinErrorLambda.errorU.lambdas.txt
cat CompositeRob/sim1_500_CompositeRob_500_uplim_MinErrorLambda_error.lambdas_* > friedman1_500_CompositeRob_500_uplim_MinErrorLambda.error.lambdas.txt


## November 2017 
## For CART, DC and Thirds method with large sample sizes


cat justCART/November2017/sim1_5000_justCART_Train5000_PRUNED_*ErrorToTruthCurrent* > Pop_500_justCART_Train5000_pruned_ErrorToTruth.txt
cat justCART/November2017/sim1_5000_justCART_Train5000_PRUNED_*SizeTreeTerminalNodes* > Pop_500_justCART_Train5000_pruned_SizeTreeTerminalNodes.txt

cat CompositeDC/November2017/sim1_5000_CompositeDC_Train5000_PRUNED_*MinErrorLambda* > Pop_500_CompositeDC_Train5000_uplim_MinErrorLambda.txt
cat CompositeDC/November2017/sim1_5000_CompositeDC_Train5000_PRUNED_*SizeTreeTerminalNodes* > Pop_500_CompositeDC_Train5000_uplim_SizeTreeTerminalNodes.txt
cat CompositeDC/November2017/sim1_5000_CompositeDC_Train5000_PRUNED_*ErrorToTruthCurrent* > Pop_500_CompositeDC_Train5000_uplim_ErrorToTruthCurrent.txt

cat CompositeThirds/November2017/sim1_5000_CompositeThirds_5000_uplim_*MinErrorLambda* > Pop_500_CompositeThirds_5000_uplim_ALPHA1_MinErrorLambda.txt
cat CompositeThirds/November2017/sim1_5000_CompositeThirds_5000_uplim_*ErrorToTruthCurrent* > Pop_500_CompositeThirds_5000_uplim_ALPHA1_ErrorToTruthCurrent.txt
cat CompositeThirds/November2017/sim1_5000_CompositeThirds_5000_uplim_*SizeTreeTerminalNodes* > Pop_500_CompositeThirds_5000_uplim_ALPHA1_SizeTreeTerminalNodes.txt


cat CompositeThirds/November2017/NoAlpha/sim1_5000_CompositeThirds_5000_uplim_*MinErrorLambda* > Pop_500_CompositeThirds_5000_uplim_MinErrorLambda.txt
cat CompositeThirds/November2017/NoAlpha/sim1_5000_CompositeThirds_5000_uplim_*ErrorToTruthCurrent* > Pop_500_CompositeThirds_5000_uplim_ErrorToTruthCurrent.txt
cat CompositeThirds/November2017/NoAlpha/sim1_5000_CompositeThirds_5000_uplim_*SizeTreeTerminalNodes* > Pop_500_CompositeThirds_5000_uplim_SizeTreeTerminalNodes.txt